title: yby's blog
description: 数据笔记与碎思
author: yby
baseurl: ""
url: "https://byyanxx.github.io"
repo_url: "https://github.com/byYanXX/byYanXX.github.io"
lang: zh-CN

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Asia/Shanghai
future: true

collections:
  notes:
    output: true
    permalink: /notes/:path/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: notes
    values:
      layout: note

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - README.md
  - .gitignore
